server:
  port: 8088
  contextPath: boot

car:
  carName: Toyota Supra
  carNo: 9091

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"